language: php
php:
- 7.1
sudo: false
script:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: YJ7QkCWX8ijZJPLcbIrZxpOrNUYGK9mvnW+idzxLkUuZrOdONDCV9EgDkfuR5ekzJ6gx7TmA8kEirXpd7MiP8ld0CjZB8K2HLP72ii5XbHDL50Ul/eoqo7XGhUd7eTDBjOWVJj0VnaQ/1JEg+qapHTTVUxo16G25sq5JAHxEKH3XOQyZWZo8n6zmp771Pm0bu+X9zNoMRy1kldUjbh6IPJ4OoNEfrTCzVlzkRzHXDP+daXdnWQne02TLfWquOamM4cGVGYTfMfLq6nyNN/m4V1vxXJ7E1fK7aagc413oMHH00s+Vm+JJYBeRBVSLU8WpvL1+byZgr55VwIZVEzh9KgptWfcWbWYmg9EO1DPBdk85PyA69rnw6b1ckMO8TtTLNNVRGBRZRyIorbvrQA0u9327t4fzsacBnoVcK8SdG+b/TYTnxNnBEhOZ/FvUrNWVeBjcPLhCA3xVNCFwMZedz+XwEq43aCJRVvl0sNyOtbHDG8nXs7Z1MSb//l36h5N9TBSpBGoL+xX8Dyg5Sb/+K8H69BTfedO8WmOq7sDLUB9aGWG4S6wFOgylgnUFAjUzMT9UfFXraa8bvdVfR8CZfB3EmXmiV/+SGIOzrQOCwOH7Kv+gYgTEXyEsQhtFDpp9QN+rk1R2hcwNqWB7/NtoQdU4ieG+yZ7MS+hsuQ7vlXY=
  file: FroshGrafana/FroshGrafana-*.zip
  file_glob: true
  on:
    tags: true
